apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-app-prod

resources:
- ../../base

configMapGenerator:
- behavior: merge
  envs:
  - application.properties
  name: application.properties

patchesJson6902:
- path: patch_route.yaml
  target:
    kind: Route
    name: java-app-service

