apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontalpodautoscaler
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 2
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 200
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: horizontalpodautoscaler

