apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service-api.yaml
- service.yaml
- route-api.yaml
- route-mgmt.yaml
- service-hz.yaml
#- servicemonitor.yaml
#- poddisruptionbudget.yaml
#- hpa.yaml



