apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-app-preprod

resources:
- ../../base

configMapGenerator:
- behavior: merge
  envs:
  - application.properties
  name: application.properties

